version: '3.9'

services:
  synpress:
    container_name: synpress
    build: .
    environment:
      - DISPLAY=display:0.0
      - PRIVATE_KEY=${PRIVATE_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DEBUG=${DEBUG}
      - GH_PAT=${GH_PAT}
      - GH_USERNAME=${GH_USERNAME}
    depends_on:
      - display
      - video
    entrypoint: []
    working_dir: /app
    volumes:
      - ./docker/videos:/app/tests/e2e/videos
      - ./docker/screenshots:/app/tests/e2e/screenshots
    # command: >
    #   bash -c 'echo -n "======> local noVNC URL: http://localhost:8080/vnc.html?autoconnect=true " && npx wait-on http://display:8080 && yarn test:e2e'
    command: >
      bash -c 'yarn test:e2e'
    networks:
      - x11
    ipc: host
    platform: linux/arm64/v8

  display:
    container_name: display
    image: synthetixio/display:b2643097e891906524e52e7ee956260b20fa01fb-base
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
    ports:
      - '8080:8080'
    networks:
      - x11

  # ngrok:
  #   profiles:
  #     - ngrok
  #   container_name: ngrok
  #   image: synthetixio/ngrok:b2643097e891906524e52e7ee956260b20fa01fb-base
  #   ports:
  #     - '4040:4040'
  #   command:
  #     [
  #       'ngrok',
  #       'http',
  #       'display:8080',
  #       '--authtoken',
  #       '${NGROK_AUTH}'
  #     ]
  #   depends_on:
  #     - display
  #   networks:
  #     - x11

  video:
    container_name: video
    image: synthetixio/video:b2643097e891906524e52e7ee956260b20fa01fb-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
      - SE_SCREEN_WIDTH=1024
      - SE_SCREEN_HEIGHT=768
    depends_on:
      - display
    networks:
      - x11

networks:
  x11:
