name: Test App
on: [push]
jobs:
  build:
    timeout-minutes: 10
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.16]

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - name: Run headless test
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: yarn test:e2e
      #     working-directory: ./ #optional
      #     options: #optional
      #   env:
      #     CYPRESS_NETWORK_NAME: 
      #     SECRET_WORDS: alone unaware convince nation lyrics million thumb path bronze seat cargo rug
      #     NETWORK_NAME: 
      #     CYPRESS_BASE_URL: https://uniqly-app-stage-08-9375.herokuapp.com
      #     CYPRESS_DOCKER_RUN: true
      # - name: Install linux deps
      #   run: |
      #     sudo apt-get install --no-install-recommends -y \
      #     fluxbox \
      #     xvfb

      - name: Run e2e tests (headful)
        run: yarn test:e2e
        env:
          CYPRESS_NETWORK_NAME: 
          SECRET_WORDS: alone unaware convince nation lyrics million thumb path bronze seat cargo rug
          NETWORK_NAME: 
          CYPRESS_BASE_URL: https://uniqly-app-stage-08-9375.herokuapp.com
          CYPRESS_DOCKER_RUN: true
          # CYPRESS_PRIVATE_KEY_WITH_FUNDS:
          #   ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
          # GH_PAT: ${{ secrets.GH_PAT }}
          # GH_USERNAME: ${{ secrets.GH_USERNAME }}
          DISPLAY: :0.0

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        if: always()
        with:
          name: e2e-artifacts
          retention-days: 3
          path: |
            app/tests/e2e/videos
            ./tests/e2e/videos
            tests/e2e/videos
            app/tests/e2e/screenshots
        continue-on-error: true