name: Test App
on: [push]
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run and test app
        working-directory: .
        run: |
          yarn install
          yarn test:e2e
        env:
          CYPRESS_NETWORK_NAME: ''
          SECRET_WORDS: 'basket they there crop purity swing monster skin rough clap amused pumpkin'
          NETWORK_NAME: ''
          CYPRESS_BASE_URL: 'https://uniqly-app-stage-08-9375.herokuapp.com'