name: Test App
on: [push]
jobs:
  build:
    timeout-minutes: 60
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.16]

    steps:
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Run e2e tests res
        run: |
          docker-compose -f docker-compose.ci.yml up --build --exit-code-from synpress
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          DOCKER_DEFAULT_PLATFORM: linux/amd64
          CYPRESS_NETWORK_NAME: 
          SECRET_WORDS: alone unaware convince nation lyrics million thumb path bronze seat cargo rug
          NETWORK_NAME: 
          CYPRESS_BASE_URL: https://uniqly-app-stage-08-9375.herokuapp.com
          CYPRESS_DOCKER_RUN: true
          ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        if: always()
        with:
          name: e2e-artifacts
          retention-days: 3
          path: |
            app/tests/e2e/videos
            ./tests/e2e/videos
            tests/e2e/videos
            app/tests/e2e/screenshots
        continue-on-error: true